# Generated by Django 5.2.5 on 2025-08-30 13:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('Cliente', 'Cliente'), ('Vendedor', 'Vendedor'), ('Administrador', 'Administrador')], default='Cliente', max_length=15)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('email_verificado', models.BooleanField(default=False)),
                ('token_verificacao', models.UUIDField(blank=True, null=True)),
                ('token_verificacao_expiracao', models.DateTimeField(blank=True, null=True)),
                ('token_redefinir_senha', models.UUIDField(blank=True, null=True)),
                ('token_redefinir_senha_expiracao', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('pais', models.CharField(default='Brasil', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutosMonitoradosExternos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_produto', models.URLField(max_length=2048)),
                ('url_hash', models.CharField(blank=True, help_text='Hash SHA-256 da URL canônica para garantir unicidade.', max_length=64)),
                ('nome_produto', models.CharField(blank=True, max_length=255, null=True)),
                ('preco_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ultima_coleta', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoPrecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('produto_monitorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='api.produtosmonitoradosexternos')),
            ],
            options={
                'ordering': ['-data_coleta'],
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='api.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='api.sku')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='SubcategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('categoria_loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categorialoja')),
            ],
            options={
                'unique_together': {('nome', 'categoria_loja')},
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.subcategoriaproduto'),
        ),
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sugestões',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='ValorAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='api.atributo')),
            ],
            options={
                'unique_together': {('atributo', 'valor')},
            },
        ),
        migrations.AddField(
            model_name='sku',
            name='valores',
            field=models.ManyToManyField(related_name='skus', to='api.valoratributo'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome_loja', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('status_aprovacao', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado')], default='Pendente', max_length=10)),
                ('data_fundacao', models.DateField(blank=True, null=True)),
                ('horario_funcionamento', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_responsavel', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf_responsavel', models.CharField(blank=True, max_length=14, null=True)),
                ('breve_descricao_loja', models.TextField(blank=True, null=True)),
                ('logotipo_loja', models.URLField(blank=True, null=True)),
                ('site_redes_sociais', models.URLField(blank=True, null=True)),
                ('categoria_loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.categorialoja')),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.endereco')),
            ],
        ),
        migrations.AddField(
            model_name='produtosmonitoradosexternos',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vendedor'),
        ),
        migrations.AlterUniqueTogether(
            name='produtosmonitoradosexternos',
            unique_together={('vendedor', 'url_hash')},
        ),
        migrations.CreateModel(
            name='OfertaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_disponivel', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sku')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vendedor')),
            ],
            options={
                'unique_together': {('vendedor', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vendedor')),
            ],
            options={
                'unique_together': {('cliente', 'vendedor')},
            },
        ),
    ]
