# Generated by Django 5.2.6 on 2025-09-18 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produtosmonitoradosexternos',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='produtosmonitoradosexternos',
            name='vendedor',
        ),
        migrations.DeleteModel(
            name='HistoricoPrecos',
        ),
        migrations.DeleteModel(
            name='ProdutosMonitoradosExternos',
        ),
    ]
