# Generated by Django 4.2.7 on 2025-11-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_produtosmonitoradosexternos_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='nome',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='categorialoja',
            name='nome',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='logradouro',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='subcategoriaproduto',
            name='nome',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='horario_funcionamento',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='nome_loja',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
