# Generated by Django 5.2.6 on 2025-09-18 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_alter_produtosmonitoradosexternos_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_dominio', models.CharField(help_text="O nome de domínio principal, ex: 'americanas.com.br'", max_length=255, unique=True)),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para desativar temporariamente o scraping neste domínio.')),
            ],
            options={
                'verbose_name': 'Domínio',
                'verbose_name_plural': 'Domínios',
                'ordering': ['nome_dominio'],
            },
        ),
        migrations.CreateModel(
            name='ProdutosMonitoradosExternos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_produto', models.URLField(max_length=2048)),
                ('url_hash', models.CharField(blank=True, help_text='Hash SHA-256 da URL canônica para garantir unicidade.', max_length=64)),
                ('nome_produto', models.CharField(blank=True, max_length=255, null=True)),
                ('preco_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ultima_coleta', models.DateTimeField(auto_now=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vendedor')),
            ],
            options={
                'unique_together': {('vendedor', 'url_hash')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoPrecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('produto_monitorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='scraper.produtosmonitoradosexternos')),
            ],
            options={
                'ordering': ['-data_coleta'],
            },
        ),
        migrations.CreateModel(
            name='Seletor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nome', 'Nome do Produto'), ('preco', 'Preço do Produto'), ('json_ld', 'JSON-LD'), ('api_url', 'URL de API')], help_text='O tipo de dado que este seletor extrai.', max_length=10)),
                ('seletor', models.CharField(help_text='O seletor (CSS, XPath, chave JSON) ou padrão de URL.', max_length=512)),
                ('prioridade', models.PositiveSmallIntegerField(default=0, help_text='Define a ordem de tentativa (0 é a primeira).')),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seletores', to='scraper.dominio')),
            ],
            options={
                'verbose_name': 'Seletor',
                'verbose_name_plural': 'Seletores',
                'ordering': ['dominio', 'tipo', 'prioridade'],
                'unique_together': {('dominio', 'tipo', 'prioridade')},
            },
        ),
    ]
