# Generated by Django 5.2.7 on 2025-11-03 16:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_produtosmonitoradosexternos_unique_together_and_more'),
        ('scraper', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dominio',
            options={'verbose_name': 'Domínio de Scraping', 'verbose_name_plural': 'Domínios de Scraping'},
        ),
        migrations.AlterModelOptions(
            name='historicoprecos',
            options={'ordering': ['-data_coleta'], 'verbose_name': 'Histórico de Preço', 'verbose_name_plural': 'Históricos de Preços'},
        ),
        migrations.AlterModelOptions(
            name='produtosmonitoradosexternos',
            options={'verbose_name': 'Produto Monitorado Externamente', 'verbose_name_plural': 'Produtos Monitorados Externamente'},
        ),
        migrations.AlterModelOptions(
            name='seletor',
            options={'ordering': ['dominio', 'tipo', 'prioridade'], 'verbose_name': 'Seletor de Scraping', 'verbose_name_plural': 'Seletores de Scraping'},
        ),
        migrations.AlterUniqueTogether(
            name='produtosmonitoradosexternos',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='seletor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dominio',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dominio',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtosmonitoradosexternos',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seletor',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='seletor',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dominio',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dominio',
            name='nome_dominio',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='historicoprecos',
            name='produto_monitorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_precos', to='scraper.produtosmonitoradosexternos'),
        ),
        migrations.AlterField(
            model_name='produtosmonitoradosexternos',
            name='nome_produto',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produtosmonitoradosexternos',
            name='preco_atual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produtosmonitoradosexternos',
            name='url_hash',
            field=models.CharField(help_text='Hash SHA256 da URL canônica do produto.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='produtosmonitoradosexternos',
            name='url_produto',
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='produtosmonitoradosexternos',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_monitorados', to='api.vendedor'),
        ),
        migrations.AlterField(
            model_name='seletor',
            name='prioridade',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seletor',
            name='seletor',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='seletor',
            name='tipo',
            field=models.CharField(choices=[('NOME', 'Nome do Produto'), ('PRECO', 'Preço do Produto'), ('API_URL', 'URL da API de Dados')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='seletor',
            unique_together={('dominio', 'tipo', 'seletor')},
        ),
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1024)),
                ('product_name', models.CharField(max_length=512)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dado Raspado',
                'verbose_name_plural': 'Dados Raspados',
                'ordering': ['-scraped_at'],
            },
        ),
    ]
