# Generated by Django 4.2.7 on 2025-11-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_dominio_options_alter_historicoprecos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtosmonitoradosexternos',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
