# Generated by Django 5.2.5 on 2025-08-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='breve_descricao_loja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='cpf_responsavel',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='data_fundacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='horario_funcionamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='logotipo_loja',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='site_redes_sociais',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
